name: bt_sense_hat
description: View Sense Hat environment sensors via Bluetooth
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue: ^0.7.3
  synchronized: ^2.2.0+2

  cupertino_icons: ^1.0.2

dev_dependencies:
  lint: ^1.5.1
  test: ^1.15.7
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
